# Generated by Django 3.0.6 on 2021-05-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ibu_min', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('ibu_max', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('srm_min', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('srm_max', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('og_min', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('og_max', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('fg_min', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('fg_max', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('abv_min', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('abv_max', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
